apiVersion: apps/v1
kind: Deployment
metadata:
  name: filter-deployment
spec:
  selector:
    matchLabels:
      run: filter-deployment
  replicas: 1
  template:
    metadata:
      labels:
        run: filter-deployment
    spec:
      containers:
        - name: filter-container
          image: hipposareevil/filter:0.0.2
          imagePullPolicy: Always
          env:
            - name: CONSUL_PORT
              value: "443"
            - name: HOST_IP
              value: "https://saws-consul.dev.platform.einstein.com"
#              valueFrom:
#                fieldRef:
#                  fieldPath: status.hostIP
          ports:
            - containerPort: 8080
              protocol: TCP

